version: '2'

services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.7.0
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - elk

  logstash:
    image: docker.elastic.co/logstash/logstash:6.7.1
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
      - ./logstash/pipeline:/usr/share/logstash/pipeline:ro
      - ./data:/data:ro
    ports:
      - "5000:5000"
      - "9600:9600"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
      UMBRELLA_ORG_ID: ${UMBRELLA_ORG_ID}
      UMBRELLA_REPORTING_START_TS: ${UMBRELLA_REPORTING_START_TS}
      INVESTIGATE_TOKEN: ${INVESTIGATE_TOKEN}
      UMBRELLA_REPORTING_API_TOKEN: ${UMBRELLA_REPORTING_API_TOKEN}
    networks:
      - elk
    #depends_on:
    #  - elasticsearch
    entrypoint: ["/usr/share/logstash/bin/logstash"]

  kibana:
    image: docker.elastic.co/kibana/kibana:6.7.0
    volumes:
      - ./kibana/config/:/usr/share/kibana/config:ro
    ports:
      - "5601:5601"
    networks:
      - elk
    depends_on:
      - elasticsearch

networks:

  elk:
    driver: bridge
