# coding: utf-8

"""
    Cisco Secure Access API

    Unified OpenAPI spec for Cisco Secure Access APIs.

    The version of the OpenAPI document: 1.0.0
    Contact: devnet@cisco.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictFloat, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional, Union
from secure_access.models.antivirus_threats import AntivirusThreats
from secure_access.models.application import Application
from secure_access.models.category import Category
from secure_access.models.cisco_amp import CiscoAMP
from secure_access.models.data_center import DataCenter
from secure_access.models.data_loss_prevention_state import DataLossPreventionState
from secure_access.models.egress import Egress
from secure_access.models.http_error import HttpError
from secure_access.models.identity import Identity
from secure_access.models.isolated import Isolated
from secure_access.models.policy import Policy
from secure_access.models.threat import Threat
from secure_access.models.verdict import Verdict
from typing import Optional, Set
from typing_extensions import Self

class ActivityProxy(BaseModel):
    """
    The activity of the proxy.
    """ # noqa: E501
    allapplications: List[Application] = Field(description="The list of applications for the entry.")
    allowedapplications: List[Application] = Field(description="The list of allowed applications for the entry.")
    amp: CiscoAMP
    antivirusthreats: AntivirusThreats
    blockedapplications: List[Application] = Field(description="The list of blocked applications for the entry.")
    blockedfiletype: StrictStr = Field(description="The blocked file type for the entry.")
    bundleid: Union[StrictFloat, StrictInt] = Field(description="The ID of the bundle type.")
    categories: List[Category] = Field(description="The list of categories.")
    contenttype: StrictStr = Field(description="The type of web content, typically text/html.")
    datacenter: DataCenter
    datalossprevention: DataLossPreventionState
    var_date: StrictStr = Field(description="The date from the timestamp based on the timezone parameter.", alias="date")
    destinationip: StrictStr = Field(description="The destination IP for the entry.")
    egress: Egress
    externalip: StrictStr = Field(description="The external IP for the entry.")
    forwardingmethod: StrictStr = Field(description="The request method (GET, POST, HEAD, etc.)")
    httperrors: List[HttpError] = Field(description="Certificate & TLS Errors")
    identities: List[Identity] = Field(description="The list of identities for the entry.")
    internalip: StrictStr = Field(description="The internal IP for the entry.")
    isolated: Isolated
    policy: Policy
    policycategories: List[Category] = Field(description="The list of policy categories.")
    port: Optional[Union[StrictFloat, StrictInt]] = Field(description="The port used to make the request.")
    referer: StrictStr = Field(description="The referring domain or URL.")
    requestmethod: Optional[StrictStr] = Field(default=None, description="The HTTP request method.")
    requestsize: Union[StrictFloat, StrictInt] = Field(description="The response size in bytes.")
    responsefilename: StrictStr = Field(description="The response filename for the entry.")
    responsesize: Union[StrictFloat, StrictInt] = Field(description="The response size in bytes.")
    securityoverridden: StrictBool = Field(description="Specifies whether security overrides are configured.")
    sha256: StrictStr = Field(description="The hex digest of the response content.")
    statuscode: Union[StrictFloat, StrictInt] = Field(description="The HTTP status code (`200` or `201`).")
    tenantcontrols: StrictBool = Field(description="Specifies whether the request is part of a tenant control policy.")
    threats: List[Threat]
    time: StrictStr = Field(description="The time in 24-hour format based on the timezone parameter.")
    timestamp: Union[StrictFloat, StrictInt] = Field(description="The timestamp represented in milliseconds.")
    type: StrictStr = Field(description="The type of the request. A proxy request is always of type 'proxy'.")
    url: StrictStr = Field(description="The URL that was requested.")
    useragent: StrictStr = Field(description="The name of the browser that made the request.")
    verdict: Verdict
    warnstatus: StrictStr = Field(description="The warning status.")
    __properties: ClassVar[List[str]] = ["allapplications", "allowedapplications", "amp", "antivirusthreats", "blockedapplications", "blockedfiletype", "bundleid", "categories", "contenttype", "datacenter", "datalossprevention", "date", "destinationip", "egress", "externalip", "forwardingmethod", "httperrors", "identities", "internalip", "isolated", "policy", "policycategories", "port", "referer", "requestmethod", "requestsize", "responsefilename", "responsesize", "securityoverridden", "sha256", "statuscode", "tenantcontrols", "threats", "time", "timestamp", "type", "url", "useragent", "verdict", "warnstatus"]

    @field_validator('statuscode')
    def statuscode_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set([200, 201]):
            raise ValueError("must be one of enum values (200, 201)")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ActivityProxy from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in allapplications (list)
        _items = []
        if self.allapplications:
            for _item_allapplications in self.allapplications:
                if _item_allapplications:
                    _items.append(_item_allapplications.to_dict())
            _dict['allapplications'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in allowedapplications (list)
        _items = []
        if self.allowedapplications:
            for _item_allowedapplications in self.allowedapplications:
                if _item_allowedapplications:
                    _items.append(_item_allowedapplications.to_dict())
            _dict['allowedapplications'] = _items
        # override the default output from pydantic by calling `to_dict()` of amp
        if self.amp:
            _dict['amp'] = self.amp.to_dict()
        # override the default output from pydantic by calling `to_dict()` of antivirusthreats
        if self.antivirusthreats:
            _dict['antivirusthreats'] = self.antivirusthreats.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in blockedapplications (list)
        _items = []
        if self.blockedapplications:
            for _item_blockedapplications in self.blockedapplications:
                if _item_blockedapplications:
                    _items.append(_item_blockedapplications.to_dict())
            _dict['blockedapplications'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in categories (list)
        _items = []
        if self.categories:
            for _item_categories in self.categories:
                if _item_categories:
                    _items.append(_item_categories.to_dict())
            _dict['categories'] = _items
        # override the default output from pydantic by calling `to_dict()` of datacenter
        if self.datacenter:
            _dict['datacenter'] = self.datacenter.to_dict()
        # override the default output from pydantic by calling `to_dict()` of datalossprevention
        if self.datalossprevention:
            _dict['datalossprevention'] = self.datalossprevention.to_dict()
        # override the default output from pydantic by calling `to_dict()` of egress
        if self.egress:
            _dict['egress'] = self.egress.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in httperrors (list)
        _items = []
        if self.httperrors:
            for _item_httperrors in self.httperrors:
                if _item_httperrors:
                    _items.append(_item_httperrors.to_dict())
            _dict['httperrors'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in identities (list)
        _items = []
        if self.identities:
            for _item_identities in self.identities:
                if _item_identities:
                    _items.append(_item_identities.to_dict())
            _dict['identities'] = _items
        # override the default output from pydantic by calling `to_dict()` of isolated
        if self.isolated:
            _dict['isolated'] = self.isolated.to_dict()
        # override the default output from pydantic by calling `to_dict()` of policy
        if self.policy:
            _dict['policy'] = self.policy.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in policycategories (list)
        _items = []
        if self.policycategories:
            for _item_policycategories in self.policycategories:
                if _item_policycategories:
                    _items.append(_item_policycategories.to_dict())
            _dict['policycategories'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in threats (list)
        _items = []
        if self.threats:
            for _item_threats in self.threats:
                if _item_threats:
                    _items.append(_item_threats.to_dict())
            _dict['threats'] = _items
        # set to None if port (nullable) is None
        # and model_fields_set contains the field
        if self.port is None and "port" in self.model_fields_set:
            _dict['port'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ActivityProxy from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "allapplications": [Application.from_dict(_item) for _item in obj["allapplications"]] if obj.get("allapplications") is not None else None,
            "allowedapplications": [Application.from_dict(_item) for _item in obj["allowedapplications"]] if obj.get("allowedapplications") is not None else None,
            "amp": CiscoAMP.from_dict(obj["amp"]) if obj.get("amp") is not None else None,
            "antivirusthreats": AntivirusThreats.from_dict(obj["antivirusthreats"]) if obj.get("antivirusthreats") is not None else None,
            "blockedapplications": [Application.from_dict(_item) for _item in obj["blockedapplications"]] if obj.get("blockedapplications") is not None else None,
            "blockedfiletype": obj.get("blockedfiletype"),
            "bundleid": obj.get("bundleid"),
            "categories": [Category.from_dict(_item) for _item in obj["categories"]] if obj.get("categories") is not None else None,
            "contenttype": obj.get("contenttype"),
            "datacenter": DataCenter.from_dict(obj["datacenter"]) if obj.get("datacenter") is not None else None,
            "datalossprevention": DataLossPreventionState.from_dict(obj["datalossprevention"]) if obj.get("datalossprevention") is not None else None,
            "date": obj.get("date"),
            "destinationip": obj.get("destinationip"),
            "egress": Egress.from_dict(obj["egress"]) if obj.get("egress") is not None else None,
            "externalip": obj.get("externalip"),
            "forwardingmethod": obj.get("forwardingmethod"),
            "httperrors": [HttpError.from_dict(_item) for _item in obj["httperrors"]] if obj.get("httperrors") is not None else None,
            "identities": [Identity.from_dict(_item) for _item in obj["identities"]] if obj.get("identities") is not None else None,
            "internalip": obj.get("internalip"),
            "isolated": Isolated.from_dict(obj["isolated"]) if obj.get("isolated") is not None else None,
            "policy": Policy.from_dict(obj["policy"]) if obj.get("policy") is not None else None,
            "policycategories": [Category.from_dict(_item) for _item in obj["policycategories"]] if obj.get("policycategories") is not None else None,
            "port": obj.get("port"),
            "referer": obj.get("referer"),
            "requestmethod": obj.get("requestmethod"),
            "requestsize": obj.get("requestsize"),
            "responsefilename": obj.get("responsefilename"),
            "responsesize": obj.get("responsesize"),
            "securityoverridden": obj.get("securityoverridden"),
            "sha256": obj.get("sha256"),
            "statuscode": obj.get("statuscode"),
            "tenantcontrols": obj.get("tenantcontrols"),
            "threats": [Threat.from_dict(_item) for _item in obj["threats"]] if obj.get("threats") is not None else None,
            "time": obj.get("time"),
            "timestamp": obj.get("timestamp"),
            "type": obj.get("type"),
            "url": obj.get("url"),
            "useragent": obj.get("useragent"),
            "verdict": obj.get("verdict"),
            "warnstatus": obj.get("warnstatus")
        })
        return _obj


