# coding: utf-8

"""
    Cisco Secure Access API

    Unified OpenAPI spec for Cisco Secure Access APIs.

    The version of the OpenAPI document: 1.0.0
    Contact: devnet@cisco.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from secure_access.models.application_risk_vendor_compliance_inner import ApplicationRiskVendorComplianceInner
from secure_access.models.business_risk import BusinessRisk
from secure_access.models.data_storage import DataStorage
from secure_access.models.financial_viability import FinancialViability
from secure_access.models.usage_type import UsageType
from secure_access.models.weighted_risk import WeightedRisk
from typing import Optional, Set
from typing_extensions import Self

class ApplicationRisk(BaseModel):
    """
    The information about the application risk.
    """ # noqa: E501
    business_risk: Optional[BusinessRisk] = Field(default=None, alias="businessRisk")
    data_storage: Optional[DataStorage] = Field(default=None, alias="dataStorage")
    financial_viability: Optional[FinancialViability] = Field(default=None, alias="financialViability")
    id: Optional[StrictStr] = Field(default=None, description="The ID of app.")
    name: Optional[StrictStr] = Field(default=None, description="The name of the app.")
    usage_type: Optional[UsageType] = Field(default=None, alias="usageType")
    vendor_compliance: Optional[List[ApplicationRiskVendorComplianceInner]] = Field(default=None, description="The list of compliance information for the vendor.", alias="vendorCompliance")
    web_reputation: Optional[StrictInt] = Field(default=None, description="Provides accurate conclusions about a given host by tracking a broad set of attributes and using sophisticated security modeling. Powered by Talos Security Intelligence.", alias="webReputation")
    weighted_risk: Optional[WeightedRisk] = Field(default=None, alias="weightedRisk")
    __properties: ClassVar[List[str]] = ["businessRisk", "dataStorage", "financialViability", "id", "name", "usageType", "vendorCompliance", "webReputation", "weightedRisk"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ApplicationRisk from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in vendor_compliance (list)
        _items = []
        if self.vendor_compliance:
            for _item_vendor_compliance in self.vendor_compliance:
                if _item_vendor_compliance:
                    _items.append(_item_vendor_compliance.to_dict())
            _dict['vendorCompliance'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ApplicationRisk from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "businessRisk": obj.get("businessRisk"),
            "dataStorage": obj.get("dataStorage"),
            "financialViability": obj.get("financialViability"),
            "id": obj.get("id"),
            "name": obj.get("name"),
            "usageType": obj.get("usageType"),
            "vendorCompliance": [ApplicationRiskVendorComplianceInner.from_dict(_item) for _item in obj["vendorCompliance"]] if obj.get("vendorCompliance") is not None else None,
            "webReputation": obj.get("webReputation"),
            "weightedRisk": obj.get("weightedRisk")
        })
        return _obj


