# coding: utf-8

"""
    Cisco Secure Access API

    Unified OpenAPI spec for Cisco Secure Access APIs.

    The version of the OpenAPI document: 1.0.0
    Contact: devnet@cisco.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List
from secure_access.models.app_type import AppType
from secure_access.models.label import Label
from secure_access.models.sources_inner import SourcesInner
from secure_access.models.weighted_risk import WeightedRisk
from typing import Optional, Set
from typing_extensions import Self

class ApplicationInList(BaseModel):
    """
    The list of properties about the discovered apps.
    """ # noqa: E501
    app_type: AppType = Field(alias="appType")
    category: StrictStr = Field(description="The category of the app.")
    first_detected: datetime = Field(description="The date and time (ISO 8601 timestamp) when the app was first detected.", alias="firstDetected")
    id: StrictStr = Field(description="The ID of the app.")
    label: Label
    last_detected: datetime = Field(description="The date and time (ISO 8601 timestamp) when the app was last detected.", alias="lastDetected")
    name: StrictStr = Field(description="The name of the app.")
    sources: List[SourcesInner] = Field(description="The list of app sources where the sources are DNS, Web (Secure Web Gateway), and cloud-delivered firewall (CDFW) traffic events. The list can contain one or more of the source types.")
    weighted_risk: WeightedRisk = Field(alias="weightedRisk")
    __properties: ClassVar[List[str]] = ["appType", "category", "firstDetected", "id", "label", "lastDetected", "name", "sources", "weightedRisk"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ApplicationInList from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in sources (list)
        _items = []
        if self.sources:
            for _item_sources in self.sources:
                if _item_sources:
                    _items.append(_item_sources.to_dict())
            _dict['sources'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ApplicationInList from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "appType": obj.get("appType"),
            "category": obj.get("category"),
            "firstDetected": obj.get("firstDetected"),
            "id": obj.get("id"),
            "label": obj.get("label"),
            "lastDetected": obj.get("lastDetected"),
            "name": obj.get("name"),
            "sources": [SourcesInner.from_dict(_item) for _item in obj["sources"]] if obj.get("sources") is not None else None,
            "weightedRisk": obj.get("weightedRisk")
        })
        return _obj


