# coding: utf-8

"""
    Cisco Secure Access API

    Unified OpenAPI spec for Cisco Secure Access APIs.

    The version of the OpenAPI document: 1.0.0
    Contact: devnet@cisco.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from secure_access.models.apply_to import ApplyTo
from secure_access.models.system_mode import SystemMode
from typing import Optional, Set
from typing_extensions import Self

class CreateCustomIpsProfileRequest(BaseModel):
    """
    The properties of the IPS profile.
    """ # noqa: E501
    apply_to: ApplyTo = Field(alias="applyTo")
    block_list: Optional[List[StrictStr]] = Field(default=None, description="The list of signatures represented in the GID-SID format that the system will update to BLOCK. For example, move or override signature 1-28423 from WARN to BLOCK.", alias="blockList")
    ignore_list: Optional[List[StrictStr]] = Field(default=None, description="The list of signatures represented in the GID-SID format that the system will update to IGNORE. For example, move or override signature 1-28423 from BLOCK to IGNORE.", alias="ignoreList")
    name: StrictStr = Field(description="The name of the IPS Signature profile. `name` is a sequence of 1—50 characters where the string does not contain the percent (%) or asterisk (*) characters.")
    system_mode: SystemMode = Field(alias="systemMode")
    warn_list: Optional[List[StrictStr]] = Field(default=None, description="The list of signatures represented in the GID-SID format that the system will update to WARN. For example, move or override signature 1-28423 from BLOCK to WARN.", alias="warnList")
    __properties: ClassVar[List[str]] = ["applyTo", "blockList", "ignoreList", "name", "systemMode", "warnList"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CreateCustomIpsProfileRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CreateCustomIpsProfileRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "applyTo": obj.get("applyTo"),
            "blockList": obj.get("blockList"),
            "ignoreList": obj.get("ignoreList"),
            "name": obj.get("name"),
            "systemMode": obj.get("systemMode"),
            "warnList": obj.get("warnList")
        })
        return _obj


