# coding: utf-8

"""
    Cisco Secure Access API

    Unified OpenAPI spec for Cisco Secure Access APIs.

    The version of the OpenAPI document: 1.0.0
    Contact: devnet@cisco.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class Environment(str, Enum):
    """
    The type of cloud-native runtime environment that hosts the Resource Connector Group.
    """

    """
    allowed enum values
    """
    AWS = 'aws'
    AZURE = 'azure'
    CONTAINER = 'container'
    ESX = 'esx'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of Environment from a JSON string"""
        return cls(json.loads(json_str))


