# coding: utf-8

"""
    Cisco Secure Access API

    Unified OpenAPI spec for Cisco Secure Access APIs.

    The version of the OpenAPI document: 1.0.0
    Contact: devnet@cisco.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class GetBgpRoutesIp200Response(BaseModel):
    """
    The properties of the AS information.
    """ # noqa: E501
    asn: Optional[StrictStr] = Field(default=None, description="The autonomous system number (ASN) associated with the IP address.")
    cidr: Optional[StrictStr] = Field(default=None, description="The IP CIDR for the ASN.")
    creation_date: Optional[StrictStr] = Field(default=None, description="The date when the AS was first created.")
    description: Optional[StrictStr] = Field(default=None, description="Network Owner Description as provided by the network owner.")
    ir: Optional[StrictInt] = Field(default=None, description="The IR number corresponds to one of the 5 Regional Internet Registries (RIR). | Registry | Number | Region | |-----|-----|-----| | Registry | 1 | AfriNIC: Africa | | Registry | 2 | APNIC: Asia, Australia, New Zealand, and neighboring countries. | | Registry | 3 | ARIN: United States, Canada, several parts of the Caribbean region, and Antarctica. | | Registry | 4 | LACNIC: Latin America and parts of the Caribbean region. | | Registry | 5 | RIPE NCC: Europe, Russia, the Middle East, and Central Asia. | | Registry | 0 | Unknown / Not Available |")
    __properties: ClassVar[List[str]] = ["asn", "cidr", "creation_date", "description", "ir"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of GetBgpRoutesIp200Response from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of GetBgpRoutesIp200Response from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "asn": obj.get("asn"),
            "cidr": obj.get("cidr"),
            "creation_date": obj.get("creation_date"),
            "description": obj.get("description"),
            "ir": obj.get("ir")
        })
        return _obj


