# coding: utf-8

"""
    Cisco Secure Access API

    Unified OpenAPI spec for Cisco Secure Access APIs.

    The version of the OpenAPI document: 1.0.0
    Contact: devnet@cisco.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from secure_access.models.rule_action import RuleAction
from secure_access.models.rule_conditions_inner import RuleConditionsInner
from secure_access.models.setting_response_inner import SettingResponseInner
from typing import Optional, Set
from typing_extensions import Self

class RulesRuleSettingsRule(BaseModel):
    """
    The properties of the access rule that enables security for the traffic that is described on the rule. The rule includes the actions, settings, and conditions configured on the rule and when these attributes were created or modified.
    """ # noqa: E501
    created_at: Optional[datetime] = Field(default=None, description="The date and time that the rule was created.", alias="createdAt")
    modified_at: Optional[datetime] = Field(default=None, description="The date and time that the rule was modified.", alias="modifiedAt")
    modified_by: Optional[StrictStr] = Field(default=None, description="A string that includes the organization ID and user ID for the account that modified the access rule.", alias="modifiedBy")
    organization_id: Optional[StrictInt] = Field(default=None, description="The ID of the organization.", alias="organizationId")
    rule_action: Optional[RuleAction] = Field(default=None, alias="ruleAction")
    rule_conditions: Optional[List[RuleConditionsInner]] = Field(default=None, description="The list of conditions that are set on the rule. Updates to \"ReadOnly\" attributes are ignored.", alias="ruleConditions")
    rule_description: Optional[Annotated[str, Field(strict=True, max_length=256)]] = Field(default=None, description="The meaningful information about the rule. The description can have no more than 256 characters.", alias="ruleDescription")
    rule_id: Optional[StrictInt] = Field(default=None, description="The ID of the rule.", alias="ruleId")
    rule_is_default: Optional[StrictBool] = Field(default=None, description="Specifies whether the rule is the default rule.", alias="ruleIsDefault")
    rule_is_enabled: Optional[StrictBool] = Field(default=None, description="Specifies whether the rule is enabled.", alias="ruleIsEnabled")
    rule_name: Optional[Annotated[str, Field(strict=True, max_length=256)]] = Field(default=None, description="The name of the rule. The name must be unique across all rules for the organization's policy. The name can have no more than 256 characters.", alias="ruleName")
    rule_priority: Optional[StrictInt] = Field(default=None, description="The positive integer that represents the priority of the rule. The priority is unique across all rules on the policy for the organization.", alias="rulePriority")
    rule_settings: Optional[List[SettingResponseInner]] = Field(default=None, description="The properties of the policy settings.", alias="ruleSettings")
    __properties: ClassVar[List[str]] = ["createdAt", "modifiedAt", "modifiedBy", "organizationId", "ruleAction", "ruleConditions", "ruleDescription", "ruleId", "ruleIsDefault", "ruleIsEnabled", "ruleName", "rulePriority", "ruleSettings"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of RulesRuleSettingsRule from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        """
        excluded_fields: Set[str] = set([
            "created_at",
            "modified_at",
            "organization_id",
            "rule_id",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in rule_conditions (list)
        _items = []
        if self.rule_conditions:
            for _item_rule_conditions in self.rule_conditions:
                if _item_rule_conditions:
                    _items.append(_item_rule_conditions.to_dict())
            _dict['ruleConditions'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in rule_settings (list)
        _items = []
        if self.rule_settings:
            for _item_rule_settings in self.rule_settings:
                if _item_rule_settings:
                    _items.append(_item_rule_settings.to_dict())
            _dict['ruleSettings'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of RulesRuleSettingsRule from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "createdAt": obj.get("createdAt"),
            "modifiedAt": obj.get("modifiedAt"),
            "modifiedBy": obj.get("modifiedBy"),
            "organizationId": obj.get("organizationId"),
            "ruleAction": obj.get("ruleAction"),
            "ruleConditions": [RuleConditionsInner.from_dict(_item) for _item in obj["ruleConditions"]] if obj.get("ruleConditions") is not None else None,
            "ruleDescription": obj.get("ruleDescription"),
            "ruleId": obj.get("ruleId"),
            "ruleIsDefault": obj.get("ruleIsDefault"),
            "ruleIsEnabled": obj.get("ruleIsEnabled"),
            "ruleName": obj.get("ruleName"),
            "rulePriority": obj.get("rulePriority"),
            "ruleSettings": [SettingResponseInner.from_dict(_item) for _item in obj["ruleSettings"]] if obj.get("ruleSettings") is not None else None
        })
        return _obj


