# coding: utf-8

"""
    Cisco Secure Access API

    Unified OpenAPI spec for Cisco Secure Access APIs.

    The version of the OpenAPI document: 1.0.0
    Contact: devnet@cisco.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from secure_access.models.attribute_name import AttributeName
from secure_access.models.attribute_value import AttributeValue
from secure_access.models.rule_action import RuleAction
from secure_access.models.setting_name import SettingName
from secure_access.models.setting_value import SettingValue
from typing import Optional, Set
from typing_extensions import Self

class RuleFilters(BaseModel):
    """
    Filter the rules by the rule properties. **Note:** You can filter on either `ruleConditions` or the set of `sources` and `destinations` properties, but not both sets of properties.
    """ # noqa: E501
    attribute_name: Optional[AttributeName] = Field(default=None, alias="attributeName")
    attribute_value: Optional[AttributeValue] = Field(default=None, alias="attributeValue")
    rule_action: Optional[RuleAction] = Field(default=None, alias="ruleAction")
    rule_description: Optional[Annotated[str, Field(strict=True, max_length=256)]] = Field(default=None, description="The meaningful information about the rule. The description can have no more than 256 characters.", alias="ruleDescription")
    rule_is_default: Optional[StrictBool] = Field(default=None, description="Specifies whether the rule is the default rule.", alias="ruleIsDefault")
    rule_is_enabled: Optional[StrictBool] = Field(default=None, description="Specifies whether the rule is enabled.", alias="ruleIsEnabled")
    rule_name: Optional[Annotated[str, Field(strict=True, max_length=256)]] = Field(default=None, description="The name of the rule. The name must be unique across all rules for the organization's policy. The name can have no more than 256 characters.", alias="ruleName")
    rule_priority: Optional[StrictStr] = Field(default=None, description="Filter on the priorities of the rules. Provide a comma-separated string of integers that correspond to the priorities of your rules.", alias="rulePriority")
    setting_name: Optional[SettingName] = Field(default=None, alias="settingName")
    setting_value: Optional[SettingValue] = Field(default=None, alias="settingValue")
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["attributeName", "attributeValue", "ruleAction", "ruleDescription", "ruleIsDefault", "ruleIsEnabled", "ruleName", "rulePriority", "settingName", "settingValue"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of RuleFilters from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of attribute_name
        if self.attribute_name:
            _dict['attributeName'] = self.attribute_name.to_dict()
        # override the default output from pydantic by calling `to_dict()` of attribute_value
        if self.attribute_value:
            _dict['attributeValue'] = self.attribute_value.to_dict()
        # override the default output from pydantic by calling `to_dict()` of setting_value
        if self.setting_value:
            _dict['settingValue'] = self.setting_value.to_dict()
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of RuleFilters from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "attributeName": AttributeName.from_dict(obj["attributeName"]) if obj.get("attributeName") is not None else None,
            "attributeValue": AttributeValue.from_dict(obj["attributeValue"]) if obj.get("attributeValue") is not None else None,
            "ruleAction": obj.get("ruleAction"),
            "ruleDescription": obj.get("ruleDescription"),
            "ruleIsDefault": obj.get("ruleIsDefault"),
            "ruleIsEnabled": obj.get("ruleIsEnabled"),
            "ruleName": obj.get("ruleName"),
            "rulePriority": obj.get("rulePriority"),
            "settingName": obj.get("settingName"),
            "settingValue": SettingValue.from_dict(obj["settingValue"]) if obj.get("settingValue") is not None else None
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


