# coding: utf-8

"""
    Cisco Secure Access API

    Unified OpenAPI spec for Cisco Secure Access APIs.

    The version of the OpenAPI document: 1.0.0
    Contact: devnet@cisco.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class SwgSource(BaseModel):
    """
    The properties of the app's web requests.
    """ # noqa: E501
    blocked_bytes_out: Optional[StrictInt] = Field(default=None, description="The number of bytes of outbound traffic that are blocked.", alias="blockedBytesOut")
    bytes_in: Optional[StrictInt] = Field(default=None, description="The number of bytes received (inbound).", alias="bytesIn")
    bytes_out: Optional[StrictInt] = Field(default=None, description="The number of bytes sent (outbound).", alias="bytesOut")
    name: Optional[StrictStr] = Field(default=None, description="The type of traffic associated with the source.")
    total_traffic: Optional[StrictInt] = Field(default=None, description="The total number of bytes inbound and outbound for this app in your environment.", alias="totalTraffic")
    __properties: ClassVar[List[str]] = ["blockedBytesOut", "bytesIn", "bytesOut", "name", "totalTraffic"]

    @field_validator('name')
    def name_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['swg']):
            raise ValueError("must be one of enum values ('swg')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of SwgSource from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of SwgSource from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "blockedBytesOut": obj.get("blockedBytesOut"),
            "bytesIn": obj.get("bytesIn"),
            "bytesOut": obj.get("bytesOut"),
            "name": obj.get("name"),
            "totalTraffic": obj.get("totalTraffic")
        })
        return _obj


