# coding: utf-8

"""
    Cisco Secure Access API

    Unified OpenAPI spec for Cisco Secure Access APIs.

    The version of the OpenAPI document: 1.0.0
    Contact: devnet@cisco.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

import warnings
from pydantic import validate_call, Field, StrictFloat, StrictStr, StrictInt
from typing import Any, Dict, List, Optional, Tuple, Union
from typing_extensions import Annotated

from pydantic import Field, StrictBool, StrictFloat, StrictInt, StrictStr, field_validator
from typing import Optional, Union
from typing_extensions import Annotated
from secure_access.models.get_requests_by_hour200_response import GetRequestsByHour200Response

from secure_access.api_client import ApiClient, RequestSerialized
from secure_access.api_response import ApiResponse
from secure_access.rest import RESTResponseType


class OrganizationRequestsByHourApi:
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    def __init__(self, api_client=None) -> None:
        if api_client is None:
            api_client = ApiClient.get_default()
        self.api_client = api_client


    @validate_call
    def get_organization_requests_by_hour(
        self,
        type: Annotated[StrictStr, Field(description="Specify the type of traffic.")],
        var_from: Annotated[StrictStr, Field(description="A timestamp or relative time string (for example: '-1days'). Filter for data that appears after this time.")],
        to: Annotated[StrictStr, Field(description="A timestamp or relative time string (for example: 'now'). Filter for data that appears before this time.")],
        limit: Annotated[Union[StrictFloat, StrictInt], Field(description="The maximum number of records to return from the collection.")],
        offset: Annotated[Optional[Union[StrictFloat, StrictInt]], Field(description="A number that represents an index in the collection.")] = None,
        domains: Annotated[Optional[StrictStr], Field(description="A domain name or comma-delimited list of domain name.")] = None,
        urls: Annotated[Optional[StrictStr], Field(description="A URL or comma-delimited list of URL.")] = None,
        categories: Annotated[Optional[StrictStr], Field(description="A category ID or comma-delimited list of category ID.")] = None,
        policycategories: Annotated[Optional[StrictStr], Field(description="A category ID or comma-delimited list of category ID. Filter the request by the categories that trigger a policy.")] = None,
        ip: Annotated[Optional[StrictStr], Field(description="An IP address.")] = None,
        ports: Annotated[Optional[StrictStr], Field(description="A port number or comma-delimited list of port numbers.")] = None,
        identityids: Annotated[Optional[StrictStr], Field(description="An identity ID or comma-delimited list of identity IDs.")] = None,
        identitytypes: Annotated[Optional[StrictStr], Field(description="An identity type or comma-delimited list of identity types.")] = None,
        applicationid: Annotated[Optional[StrictStr], Field(description="The ID of the application.")] = None,
        verdict: Annotated[Optional[StrictStr], Field(description="A string or comma-delimited string that describes whether the traffic can reach the destination.")] = None,
        sha256: Annotated[Optional[StrictStr], Field(description="A SHA-256 hash.")] = None,
        securityoverridden: Annotated[Optional[StrictBool], Field(description="Specify whether to filter on requests that override security.")] = None,
        bundleid: Annotated[Optional[Union[StrictFloat, StrictInt]], Field(description="A proxy bundle ID.")] = None,
        threats: Annotated[Optional[StrictStr], Field(description="A threat name or comma-delimited list of threat names.")] = None,
        threattypes: Annotated[Optional[StrictStr], Field(description="A threat type or comma-delimited list of threat types.")] = None,
        ampdisposition: Annotated[Optional[StrictStr], Field(description="An AMP disposition string or a comma-delimited list of AMP disposition strings.")] = None,
        antivirusthreats: Annotated[Optional[StrictStr], Field(description="A threat name or comma-delimited list of threat names.")] = None,
        datalosspreventionstate: Annotated[Optional[StrictStr], Field(description="A string that describes the status of a destination. Filter for requests that are blocked by the DLP layer security.")] = None,
        filternoisydomains: Annotated[Optional[StrictBool], Field(description="Filter out domains that generate a lot of insignificant traffic (noise).")] = None,
        timezone: Annotated[Optional[StrictStr], Field(description="Display the timestamp of the traffic events in the specified timezone. For the timezone, provide a continent and city separated by an url-encoded forward slash ('/'), for example: timezone='ASIA%2fCALCUTTA'.")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> GetRequestsByHour200Response:
        """Get Requests by Hour

        List the activity volume within the timeframe.  **Access Scope:** Reports > Granular Events > Read-Only

        :param type: Specify the type of traffic. (required)
        :type type: str
        :param var_from: A timestamp or relative time string (for example: '-1days'). Filter for data that appears after this time. (required)
        :type var_from: str
        :param to: A timestamp or relative time string (for example: 'now'). Filter for data that appears before this time. (required)
        :type to: str
        :param limit: The maximum number of records to return from the collection. (required)
        :type limit: float
        :param offset: A number that represents an index in the collection.
        :type offset: float
        :param domains: A domain name or comma-delimited list of domain name.
        :type domains: str
        :param urls: A URL or comma-delimited list of URL.
        :type urls: str
        :param categories: A category ID or comma-delimited list of category ID.
        :type categories: str
        :param policycategories: A category ID or comma-delimited list of category ID. Filter the request by the categories that trigger a policy.
        :type policycategories: str
        :param ip: An IP address.
        :type ip: str
        :param ports: A port number or comma-delimited list of port numbers.
        :type ports: str
        :param identityids: An identity ID or comma-delimited list of identity IDs.
        :type identityids: str
        :param identitytypes: An identity type or comma-delimited list of identity types.
        :type identitytypes: str
        :param applicationid: The ID of the application.
        :type applicationid: str
        :param verdict: A string or comma-delimited string that describes whether the traffic can reach the destination.
        :type verdict: str
        :param sha256: A SHA-256 hash.
        :type sha256: str
        :param securityoverridden: Specify whether to filter on requests that override security.
        :type securityoverridden: bool
        :param bundleid: A proxy bundle ID.
        :type bundleid: float
        :param threats: A threat name or comma-delimited list of threat names.
        :type threats: str
        :param threattypes: A threat type or comma-delimited list of threat types.
        :type threattypes: str
        :param ampdisposition: An AMP disposition string or a comma-delimited list of AMP disposition strings.
        :type ampdisposition: str
        :param antivirusthreats: A threat name or comma-delimited list of threat names.
        :type antivirusthreats: str
        :param datalosspreventionstate: A string that describes the status of a destination. Filter for requests that are blocked by the DLP layer security.
        :type datalosspreventionstate: str
        :param filternoisydomains: Filter out domains that generate a lot of insignificant traffic (noise).
        :type filternoisydomains: bool
        :param timezone: Display the timestamp of the traffic events in the specified timezone. For the timezone, provide a continent and city separated by an url-encoded forward slash ('/'), for example: timezone='ASIA%2fCALCUTTA'.
        :type timezone: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._get_organization_requests_by_hour_serialize(
            type=type,
            var_from=var_from,
            to=to,
            limit=limit,
            offset=offset,
            domains=domains,
            urls=urls,
            categories=categories,
            policycategories=policycategories,
            ip=ip,
            ports=ports,
            identityids=identityids,
            identitytypes=identitytypes,
            applicationid=applicationid,
            verdict=verdict,
            sha256=sha256,
            securityoverridden=securityoverridden,
            bundleid=bundleid,
            threats=threats,
            threattypes=threattypes,
            ampdisposition=ampdisposition,
            antivirusthreats=antivirusthreats,
            datalosspreventionstate=datalosspreventionstate,
            filternoisydomains=filternoisydomains,
            timezone=timezone,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "GetRequestsByHour200Response",
            '400': "Reporting400Error",
            '401': "Reporting401Error",
            '403': "Reporting403Error",
            '404': "Reporting404Error",
            '500': "Reporting500Error",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    def get_organization_requests_by_hour_with_http_info(
        self,
        type: Annotated[StrictStr, Field(description="Specify the type of traffic.")],
        var_from: Annotated[StrictStr, Field(description="A timestamp or relative time string (for example: '-1days'). Filter for data that appears after this time.")],
        to: Annotated[StrictStr, Field(description="A timestamp or relative time string (for example: 'now'). Filter for data that appears before this time.")],
        limit: Annotated[Union[StrictFloat, StrictInt], Field(description="The maximum number of records to return from the collection.")],
        offset: Annotated[Optional[Union[StrictFloat, StrictInt]], Field(description="A number that represents an index in the collection.")] = None,
        domains: Annotated[Optional[StrictStr], Field(description="A domain name or comma-delimited list of domain name.")] = None,
        urls: Annotated[Optional[StrictStr], Field(description="A URL or comma-delimited list of URL.")] = None,
        categories: Annotated[Optional[StrictStr], Field(description="A category ID or comma-delimited list of category ID.")] = None,
        policycategories: Annotated[Optional[StrictStr], Field(description="A category ID or comma-delimited list of category ID. Filter the request by the categories that trigger a policy.")] = None,
        ip: Annotated[Optional[StrictStr], Field(description="An IP address.")] = None,
        ports: Annotated[Optional[StrictStr], Field(description="A port number or comma-delimited list of port numbers.")] = None,
        identityids: Annotated[Optional[StrictStr], Field(description="An identity ID or comma-delimited list of identity IDs.")] = None,
        identitytypes: Annotated[Optional[StrictStr], Field(description="An identity type or comma-delimited list of identity types.")] = None,
        applicationid: Annotated[Optional[StrictStr], Field(description="The ID of the application.")] = None,
        verdict: Annotated[Optional[StrictStr], Field(description="A string or comma-delimited string that describes whether the traffic can reach the destination.")] = None,
        sha256: Annotated[Optional[StrictStr], Field(description="A SHA-256 hash.")] = None,
        securityoverridden: Annotated[Optional[StrictBool], Field(description="Specify whether to filter on requests that override security.")] = None,
        bundleid: Annotated[Optional[Union[StrictFloat, StrictInt]], Field(description="A proxy bundle ID.")] = None,
        threats: Annotated[Optional[StrictStr], Field(description="A threat name or comma-delimited list of threat names.")] = None,
        threattypes: Annotated[Optional[StrictStr], Field(description="A threat type or comma-delimited list of threat types.")] = None,
        ampdisposition: Annotated[Optional[StrictStr], Field(description="An AMP disposition string or a comma-delimited list of AMP disposition strings.")] = None,
        antivirusthreats: Annotated[Optional[StrictStr], Field(description="A threat name or comma-delimited list of threat names.")] = None,
        datalosspreventionstate: Annotated[Optional[StrictStr], Field(description="A string that describes the status of a destination. Filter for requests that are blocked by the DLP layer security.")] = None,
        filternoisydomains: Annotated[Optional[StrictBool], Field(description="Filter out domains that generate a lot of insignificant traffic (noise).")] = None,
        timezone: Annotated[Optional[StrictStr], Field(description="Display the timestamp of the traffic events in the specified timezone. For the timezone, provide a continent and city separated by an url-encoded forward slash ('/'), for example: timezone='ASIA%2fCALCUTTA'.")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[GetRequestsByHour200Response]:
        """Get Requests by Hour

        List the activity volume within the timeframe.  **Access Scope:** Reports > Granular Events > Read-Only

        :param type: Specify the type of traffic. (required)
        :type type: str
        :param var_from: A timestamp or relative time string (for example: '-1days'). Filter for data that appears after this time. (required)
        :type var_from: str
        :param to: A timestamp or relative time string (for example: 'now'). Filter for data that appears before this time. (required)
        :type to: str
        :param limit: The maximum number of records to return from the collection. (required)
        :type limit: float
        :param offset: A number that represents an index in the collection.
        :type offset: float
        :param domains: A domain name or comma-delimited list of domain name.
        :type domains: str
        :param urls: A URL or comma-delimited list of URL.
        :type urls: str
        :param categories: A category ID or comma-delimited list of category ID.
        :type categories: str
        :param policycategories: A category ID or comma-delimited list of category ID. Filter the request by the categories that trigger a policy.
        :type policycategories: str
        :param ip: An IP address.
        :type ip: str
        :param ports: A port number or comma-delimited list of port numbers.
        :type ports: str
        :param identityids: An identity ID or comma-delimited list of identity IDs.
        :type identityids: str
        :param identitytypes: An identity type or comma-delimited list of identity types.
        :type identitytypes: str
        :param applicationid: The ID of the application.
        :type applicationid: str
        :param verdict: A string or comma-delimited string that describes whether the traffic can reach the destination.
        :type verdict: str
        :param sha256: A SHA-256 hash.
        :type sha256: str
        :param securityoverridden: Specify whether to filter on requests that override security.
        :type securityoverridden: bool
        :param bundleid: A proxy bundle ID.
        :type bundleid: float
        :param threats: A threat name or comma-delimited list of threat names.
        :type threats: str
        :param threattypes: A threat type or comma-delimited list of threat types.
        :type threattypes: str
        :param ampdisposition: An AMP disposition string or a comma-delimited list of AMP disposition strings.
        :type ampdisposition: str
        :param antivirusthreats: A threat name or comma-delimited list of threat names.
        :type antivirusthreats: str
        :param datalosspreventionstate: A string that describes the status of a destination. Filter for requests that are blocked by the DLP layer security.
        :type datalosspreventionstate: str
        :param filternoisydomains: Filter out domains that generate a lot of insignificant traffic (noise).
        :type filternoisydomains: bool
        :param timezone: Display the timestamp of the traffic events in the specified timezone. For the timezone, provide a continent and city separated by an url-encoded forward slash ('/'), for example: timezone='ASIA%2fCALCUTTA'.
        :type timezone: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._get_organization_requests_by_hour_serialize(
            type=type,
            var_from=var_from,
            to=to,
            limit=limit,
            offset=offset,
            domains=domains,
            urls=urls,
            categories=categories,
            policycategories=policycategories,
            ip=ip,
            ports=ports,
            identityids=identityids,
            identitytypes=identitytypes,
            applicationid=applicationid,
            verdict=verdict,
            sha256=sha256,
            securityoverridden=securityoverridden,
            bundleid=bundleid,
            threats=threats,
            threattypes=threattypes,
            ampdisposition=ampdisposition,
            antivirusthreats=antivirusthreats,
            datalosspreventionstate=datalosspreventionstate,
            filternoisydomains=filternoisydomains,
            timezone=timezone,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "GetRequestsByHour200Response",
            '400': "Reporting400Error",
            '401': "Reporting401Error",
            '403': "Reporting403Error",
            '404': "Reporting404Error",
            '500': "Reporting500Error",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    def get_organization_requests_by_hour_without_preload_content(
        self,
        type: Annotated[StrictStr, Field(description="Specify the type of traffic.")],
        var_from: Annotated[StrictStr, Field(description="A timestamp or relative time string (for example: '-1days'). Filter for data that appears after this time.")],
        to: Annotated[StrictStr, Field(description="A timestamp or relative time string (for example: 'now'). Filter for data that appears before this time.")],
        limit: Annotated[Union[StrictFloat, StrictInt], Field(description="The maximum number of records to return from the collection.")],
        offset: Annotated[Optional[Union[StrictFloat, StrictInt]], Field(description="A number that represents an index in the collection.")] = None,
        domains: Annotated[Optional[StrictStr], Field(description="A domain name or comma-delimited list of domain name.")] = None,
        urls: Annotated[Optional[StrictStr], Field(description="A URL or comma-delimited list of URL.")] = None,
        categories: Annotated[Optional[StrictStr], Field(description="A category ID or comma-delimited list of category ID.")] = None,
        policycategories: Annotated[Optional[StrictStr], Field(description="A category ID or comma-delimited list of category ID. Filter the request by the categories that trigger a policy.")] = None,
        ip: Annotated[Optional[StrictStr], Field(description="An IP address.")] = None,
        ports: Annotated[Optional[StrictStr], Field(description="A port number or comma-delimited list of port numbers.")] = None,
        identityids: Annotated[Optional[StrictStr], Field(description="An identity ID or comma-delimited list of identity IDs.")] = None,
        identitytypes: Annotated[Optional[StrictStr], Field(description="An identity type or comma-delimited list of identity types.")] = None,
        applicationid: Annotated[Optional[StrictStr], Field(description="The ID of the application.")] = None,
        verdict: Annotated[Optional[StrictStr], Field(description="A string or comma-delimited string that describes whether the traffic can reach the destination.")] = None,
        sha256: Annotated[Optional[StrictStr], Field(description="A SHA-256 hash.")] = None,
        securityoverridden: Annotated[Optional[StrictBool], Field(description="Specify whether to filter on requests that override security.")] = None,
        bundleid: Annotated[Optional[Union[StrictFloat, StrictInt]], Field(description="A proxy bundle ID.")] = None,
        threats: Annotated[Optional[StrictStr], Field(description="A threat name or comma-delimited list of threat names.")] = None,
        threattypes: Annotated[Optional[StrictStr], Field(description="A threat type or comma-delimited list of threat types.")] = None,
        ampdisposition: Annotated[Optional[StrictStr], Field(description="An AMP disposition string or a comma-delimited list of AMP disposition strings.")] = None,
        antivirusthreats: Annotated[Optional[StrictStr], Field(description="A threat name or comma-delimited list of threat names.")] = None,
        datalosspreventionstate: Annotated[Optional[StrictStr], Field(description="A string that describes the status of a destination. Filter for requests that are blocked by the DLP layer security.")] = None,
        filternoisydomains: Annotated[Optional[StrictBool], Field(description="Filter out domains that generate a lot of insignificant traffic (noise).")] = None,
        timezone: Annotated[Optional[StrictStr], Field(description="Display the timestamp of the traffic events in the specified timezone. For the timezone, provide a continent and city separated by an url-encoded forward slash ('/'), for example: timezone='ASIA%2fCALCUTTA'.")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """Get Requests by Hour

        List the activity volume within the timeframe.  **Access Scope:** Reports > Granular Events > Read-Only

        :param type: Specify the type of traffic. (required)
        :type type: str
        :param var_from: A timestamp or relative time string (for example: '-1days'). Filter for data that appears after this time. (required)
        :type var_from: str
        :param to: A timestamp or relative time string (for example: 'now'). Filter for data that appears before this time. (required)
        :type to: str
        :param limit: The maximum number of records to return from the collection. (required)
        :type limit: float
        :param offset: A number that represents an index in the collection.
        :type offset: float
        :param domains: A domain name or comma-delimited list of domain name.
        :type domains: str
        :param urls: A URL or comma-delimited list of URL.
        :type urls: str
        :param categories: A category ID or comma-delimited list of category ID.
        :type categories: str
        :param policycategories: A category ID or comma-delimited list of category ID. Filter the request by the categories that trigger a policy.
        :type policycategories: str
        :param ip: An IP address.
        :type ip: str
        :param ports: A port number or comma-delimited list of port numbers.
        :type ports: str
        :param identityids: An identity ID or comma-delimited list of identity IDs.
        :type identityids: str
        :param identitytypes: An identity type or comma-delimited list of identity types.
        :type identitytypes: str
        :param applicationid: The ID of the application.
        :type applicationid: str
        :param verdict: A string or comma-delimited string that describes whether the traffic can reach the destination.
        :type verdict: str
        :param sha256: A SHA-256 hash.
        :type sha256: str
        :param securityoverridden: Specify whether to filter on requests that override security.
        :type securityoverridden: bool
        :param bundleid: A proxy bundle ID.
        :type bundleid: float
        :param threats: A threat name or comma-delimited list of threat names.
        :type threats: str
        :param threattypes: A threat type or comma-delimited list of threat types.
        :type threattypes: str
        :param ampdisposition: An AMP disposition string or a comma-delimited list of AMP disposition strings.
        :type ampdisposition: str
        :param antivirusthreats: A threat name or comma-delimited list of threat names.
        :type antivirusthreats: str
        :param datalosspreventionstate: A string that describes the status of a destination. Filter for requests that are blocked by the DLP layer security.
        :type datalosspreventionstate: str
        :param filternoisydomains: Filter out domains that generate a lot of insignificant traffic (noise).
        :type filternoisydomains: bool
        :param timezone: Display the timestamp of the traffic events in the specified timezone. For the timezone, provide a continent and city separated by an url-encoded forward slash ('/'), for example: timezone='ASIA%2fCALCUTTA'.
        :type timezone: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._get_organization_requests_by_hour_serialize(
            type=type,
            var_from=var_from,
            to=to,
            limit=limit,
            offset=offset,
            domains=domains,
            urls=urls,
            categories=categories,
            policycategories=policycategories,
            ip=ip,
            ports=ports,
            identityids=identityids,
            identitytypes=identitytypes,
            applicationid=applicationid,
            verdict=verdict,
            sha256=sha256,
            securityoverridden=securityoverridden,
            bundleid=bundleid,
            threats=threats,
            threattypes=threattypes,
            ampdisposition=ampdisposition,
            antivirusthreats=antivirusthreats,
            datalosspreventionstate=datalosspreventionstate,
            filternoisydomains=filternoisydomains,
            timezone=timezone,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "GetRequestsByHour200Response",
            '400': "Reporting400Error",
            '401': "Reporting401Error",
            '403': "Reporting403Error",
            '404': "Reporting404Error",
            '500': "Reporting500Error",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _get_organization_requests_by_hour_serialize(
        self,
        type,
        var_from,
        to,
        limit,
        offset,
        domains,
        urls,
        categories,
        policycategories,
        ip,
        ports,
        identityids,
        identitytypes,
        applicationid,
        verdict,
        sha256,
        securityoverridden,
        bundleid,
        threats,
        threattypes,
        ampdisposition,
        antivirusthreats,
        datalosspreventionstate,
        filternoisydomains,
        timezone,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[
            str, Union[str, bytes, List[str], List[bytes], List[Tuple[str, bytes]]]
        ] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        if type is not None:
            _path_params['type'] = type
        # process the query parameters
        if var_from is not None:
            
            _query_params.append(('from', var_from))
            
        if to is not None:
            
            _query_params.append(('to', to))
            
        if limit is not None:
            
            _query_params.append(('limit', limit))
            
        if offset is not None:
            
            _query_params.append(('offset', offset))
            
        if domains is not None:
            
            _query_params.append(('domains', domains))
            
        if urls is not None:
            
            _query_params.append(('urls', urls))
            
        if categories is not None:
            
            _query_params.append(('categories', categories))
            
        if policycategories is not None:
            
            _query_params.append(('policycategories', policycategories))
            
        if ip is not None:
            
            _query_params.append(('ip', ip))
            
        if ports is not None:
            
            _query_params.append(('ports', ports))
            
        if identityids is not None:
            
            _query_params.append(('identityids', identityids))
            
        if identitytypes is not None:
            
            _query_params.append(('identitytypes', identitytypes))
            
        if applicationid is not None:
            
            _query_params.append(('applicationid', applicationid))
            
        if verdict is not None:
            
            _query_params.append(('verdict', verdict))
            
        if sha256 is not None:
            
            _query_params.append(('sha256', sha256))
            
        if securityoverridden is not None:
            
            _query_params.append(('securityoverridden', securityoverridden))
            
        if bundleid is not None:
            
            _query_params.append(('bundleid', bundleid))
            
        if threats is not None:
            
            _query_params.append(('threats', threats))
            
        if threattypes is not None:
            
            _query_params.append(('threattypes', threattypes))
            
        if ampdisposition is not None:
            
            _query_params.append(('ampdisposition', ampdisposition))
            
        if antivirusthreats is not None:
            
            _query_params.append(('antivirusthreats', antivirusthreats))
            
        if datalosspreventionstate is not None:
            
            _query_params.append(('datalosspreventionstate', datalosspreventionstate))
            
        if filternoisydomains is not None:
            
            _query_params.append(('filternoisydomains', filternoisydomains))
            
        if timezone is not None:
            
            _query_params.append(('timezone', timezone))
            
        # process the header parameters
        # process the form parameters
        # process the body parameter


        # set the HTTP header `Accept`
        if 'Accept' not in _header_params:
            _header_params['Accept'] = self.api_client.select_header_accept(
                [
                    'application/json'
                ]
            )


        # authentication setting
        _auth_settings: List[str] = [
            'oauthFlow'
        ]

        return self.api_client.param_serialize(
            method='GET',
            resource_path='/reports/v2/requests-by-hour/{type}',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )




    @validate_call
    def get_requests_by_hour(
        self,
        var_from: Annotated[StrictStr, Field(description="A timestamp or relative time string (for example: '-1days'). Filter for data that appears after this time.")],
        to: Annotated[StrictStr, Field(description="A timestamp or relative time string (for example: 'now'). Filter for data that appears before this time.")],
        limit: Annotated[Union[StrictFloat, StrictInt], Field(description="The maximum number of records to return from the collection.")],
        offset: Annotated[Optional[Union[StrictFloat, StrictInt]], Field(description="A number that represents an index in the collection.")] = None,
        domains: Annotated[Optional[StrictStr], Field(description="A domain name or comma-delimited list of domain name.")] = None,
        urls: Annotated[Optional[StrictStr], Field(description="A URL or comma-delimited list of URL.")] = None,
        categories: Annotated[Optional[StrictStr], Field(description="A category ID or comma-delimited list of category ID.")] = None,
        policycategories: Annotated[Optional[StrictStr], Field(description="A category ID or comma-delimited list of category ID. Filter the request by the categories that trigger a policy.")] = None,
        ip: Annotated[Optional[StrictStr], Field(description="An IP address.")] = None,
        ports: Annotated[Optional[StrictStr], Field(description="A port number or comma-delimited list of port numbers.")] = None,
        identityids: Annotated[Optional[StrictStr], Field(description="An identity ID or comma-delimited list of identity IDs.")] = None,
        identitytypes: Annotated[Optional[StrictStr], Field(description="An identity type or comma-delimited list of identity types.")] = None,
        applicationid: Annotated[Optional[StrictStr], Field(description="The ID of the application.")] = None,
        verdict: Annotated[Optional[StrictStr], Field(description="A string or comma-delimited string that describes whether the traffic can reach the destination.")] = None,
        sha256: Annotated[Optional[StrictStr], Field(description="A SHA-256 hash.")] = None,
        securityoverridden: Annotated[Optional[StrictBool], Field(description="Specify whether to filter on requests that override security.")] = None,
        bundleid: Annotated[Optional[Union[StrictFloat, StrictInt]], Field(description="A proxy bundle ID.")] = None,
        threats: Annotated[Optional[StrictStr], Field(description="A threat name or comma-delimited list of threat names.")] = None,
        threattypes: Annotated[Optional[StrictStr], Field(description="A threat type or comma-delimited list of threat types.")] = None,
        ampdisposition: Annotated[Optional[StrictStr], Field(description="An AMP disposition string or a comma-delimited list of AMP disposition strings.")] = None,
        antivirusthreats: Annotated[Optional[StrictStr], Field(description="A threat name or comma-delimited list of threat names.")] = None,
        datalosspreventionstate: Annotated[Optional[StrictStr], Field(description="A string that describes the status of a destination. Filter for requests that are blocked by the DLP layer security.")] = None,
        filternoisydomains: Annotated[Optional[StrictBool], Field(description="Filter out domains that generate a lot of insignificant traffic (noise).")] = None,
        timezone: Annotated[Optional[StrictStr], Field(description="Display the timestamp of the traffic events in the specified timezone. For the timezone, provide a continent and city separated by an url-encoded forward slash ('/'), for example: timezone='ASIA%2fCALCUTTA'.")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> GetRequestsByHour200Response:
        """Get Requests by Hour (All)

        List the activity volume within the timeframe.  **Access Scope:** Reports > Granular Events > Read-Only

        :param var_from: A timestamp or relative time string (for example: '-1days'). Filter for data that appears after this time. (required)
        :type var_from: str
        :param to: A timestamp or relative time string (for example: 'now'). Filter for data that appears before this time. (required)
        :type to: str
        :param limit: The maximum number of records to return from the collection. (required)
        :type limit: float
        :param offset: A number that represents an index in the collection.
        :type offset: float
        :param domains: A domain name or comma-delimited list of domain name.
        :type domains: str
        :param urls: A URL or comma-delimited list of URL.
        :type urls: str
        :param categories: A category ID or comma-delimited list of category ID.
        :type categories: str
        :param policycategories: A category ID or comma-delimited list of category ID. Filter the request by the categories that trigger a policy.
        :type policycategories: str
        :param ip: An IP address.
        :type ip: str
        :param ports: A port number or comma-delimited list of port numbers.
        :type ports: str
        :param identityids: An identity ID or comma-delimited list of identity IDs.
        :type identityids: str
        :param identitytypes: An identity type or comma-delimited list of identity types.
        :type identitytypes: str
        :param applicationid: The ID of the application.
        :type applicationid: str
        :param verdict: A string or comma-delimited string that describes whether the traffic can reach the destination.
        :type verdict: str
        :param sha256: A SHA-256 hash.
        :type sha256: str
        :param securityoverridden: Specify whether to filter on requests that override security.
        :type securityoverridden: bool
        :param bundleid: A proxy bundle ID.
        :type bundleid: float
        :param threats: A threat name or comma-delimited list of threat names.
        :type threats: str
        :param threattypes: A threat type or comma-delimited list of threat types.
        :type threattypes: str
        :param ampdisposition: An AMP disposition string or a comma-delimited list of AMP disposition strings.
        :type ampdisposition: str
        :param antivirusthreats: A threat name or comma-delimited list of threat names.
        :type antivirusthreats: str
        :param datalosspreventionstate: A string that describes the status of a destination. Filter for requests that are blocked by the DLP layer security.
        :type datalosspreventionstate: str
        :param filternoisydomains: Filter out domains that generate a lot of insignificant traffic (noise).
        :type filternoisydomains: bool
        :param timezone: Display the timestamp of the traffic events in the specified timezone. For the timezone, provide a continent and city separated by an url-encoded forward slash ('/'), for example: timezone='ASIA%2fCALCUTTA'.
        :type timezone: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._get_requests_by_hour_serialize(
            var_from=var_from,
            to=to,
            limit=limit,
            offset=offset,
            domains=domains,
            urls=urls,
            categories=categories,
            policycategories=policycategories,
            ip=ip,
            ports=ports,
            identityids=identityids,
            identitytypes=identitytypes,
            applicationid=applicationid,
            verdict=verdict,
            sha256=sha256,
            securityoverridden=securityoverridden,
            bundleid=bundleid,
            threats=threats,
            threattypes=threattypes,
            ampdisposition=ampdisposition,
            antivirusthreats=antivirusthreats,
            datalosspreventionstate=datalosspreventionstate,
            filternoisydomains=filternoisydomains,
            timezone=timezone,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "GetRequestsByHour200Response",
            '400': "Reporting400Error",
            '401': "Reporting401Error",
            '403': "Reporting403Error",
            '404': "Reporting404Error",
            '500': "Reporting500Error",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    def get_requests_by_hour_with_http_info(
        self,
        var_from: Annotated[StrictStr, Field(description="A timestamp or relative time string (for example: '-1days'). Filter for data that appears after this time.")],
        to: Annotated[StrictStr, Field(description="A timestamp or relative time string (for example: 'now'). Filter for data that appears before this time.")],
        limit: Annotated[Union[StrictFloat, StrictInt], Field(description="The maximum number of records to return from the collection.")],
        offset: Annotated[Optional[Union[StrictFloat, StrictInt]], Field(description="A number that represents an index in the collection.")] = None,
        domains: Annotated[Optional[StrictStr], Field(description="A domain name or comma-delimited list of domain name.")] = None,
        urls: Annotated[Optional[StrictStr], Field(description="A URL or comma-delimited list of URL.")] = None,
        categories: Annotated[Optional[StrictStr], Field(description="A category ID or comma-delimited list of category ID.")] = None,
        policycategories: Annotated[Optional[StrictStr], Field(description="A category ID or comma-delimited list of category ID. Filter the request by the categories that trigger a policy.")] = None,
        ip: Annotated[Optional[StrictStr], Field(description="An IP address.")] = None,
        ports: Annotated[Optional[StrictStr], Field(description="A port number or comma-delimited list of port numbers.")] = None,
        identityids: Annotated[Optional[StrictStr], Field(description="An identity ID or comma-delimited list of identity IDs.")] = None,
        identitytypes: Annotated[Optional[StrictStr], Field(description="An identity type or comma-delimited list of identity types.")] = None,
        applicationid: Annotated[Optional[StrictStr], Field(description="The ID of the application.")] = None,
        verdict: Annotated[Optional[StrictStr], Field(description="A string or comma-delimited string that describes whether the traffic can reach the destination.")] = None,
        sha256: Annotated[Optional[StrictStr], Field(description="A SHA-256 hash.")] = None,
        securityoverridden: Annotated[Optional[StrictBool], Field(description="Specify whether to filter on requests that override security.")] = None,
        bundleid: Annotated[Optional[Union[StrictFloat, StrictInt]], Field(description="A proxy bundle ID.")] = None,
        threats: Annotated[Optional[StrictStr], Field(description="A threat name or comma-delimited list of threat names.")] = None,
        threattypes: Annotated[Optional[StrictStr], Field(description="A threat type or comma-delimited list of threat types.")] = None,
        ampdisposition: Annotated[Optional[StrictStr], Field(description="An AMP disposition string or a comma-delimited list of AMP disposition strings.")] = None,
        antivirusthreats: Annotated[Optional[StrictStr], Field(description="A threat name or comma-delimited list of threat names.")] = None,
        datalosspreventionstate: Annotated[Optional[StrictStr], Field(description="A string that describes the status of a destination. Filter for requests that are blocked by the DLP layer security.")] = None,
        filternoisydomains: Annotated[Optional[StrictBool], Field(description="Filter out domains that generate a lot of insignificant traffic (noise).")] = None,
        timezone: Annotated[Optional[StrictStr], Field(description="Display the timestamp of the traffic events in the specified timezone. For the timezone, provide a continent and city separated by an url-encoded forward slash ('/'), for example: timezone='ASIA%2fCALCUTTA'.")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[GetRequestsByHour200Response]:
        """Get Requests by Hour (All)

        List the activity volume within the timeframe.  **Access Scope:** Reports > Granular Events > Read-Only

        :param var_from: A timestamp or relative time string (for example: '-1days'). Filter for data that appears after this time. (required)
        :type var_from: str
        :param to: A timestamp or relative time string (for example: 'now'). Filter for data that appears before this time. (required)
        :type to: str
        :param limit: The maximum number of records to return from the collection. (required)
        :type limit: float
        :param offset: A number that represents an index in the collection.
        :type offset: float
        :param domains: A domain name or comma-delimited list of domain name.
        :type domains: str
        :param urls: A URL or comma-delimited list of URL.
        :type urls: str
        :param categories: A category ID or comma-delimited list of category ID.
        :type categories: str
        :param policycategories: A category ID or comma-delimited list of category ID. Filter the request by the categories that trigger a policy.
        :type policycategories: str
        :param ip: An IP address.
        :type ip: str
        :param ports: A port number or comma-delimited list of port numbers.
        :type ports: str
        :param identityids: An identity ID or comma-delimited list of identity IDs.
        :type identityids: str
        :param identitytypes: An identity type or comma-delimited list of identity types.
        :type identitytypes: str
        :param applicationid: The ID of the application.
        :type applicationid: str
        :param verdict: A string or comma-delimited string that describes whether the traffic can reach the destination.
        :type verdict: str
        :param sha256: A SHA-256 hash.
        :type sha256: str
        :param securityoverridden: Specify whether to filter on requests that override security.
        :type securityoverridden: bool
        :param bundleid: A proxy bundle ID.
        :type bundleid: float
        :param threats: A threat name or comma-delimited list of threat names.
        :type threats: str
        :param threattypes: A threat type or comma-delimited list of threat types.
        :type threattypes: str
        :param ampdisposition: An AMP disposition string or a comma-delimited list of AMP disposition strings.
        :type ampdisposition: str
        :param antivirusthreats: A threat name or comma-delimited list of threat names.
        :type antivirusthreats: str
        :param datalosspreventionstate: A string that describes the status of a destination. Filter for requests that are blocked by the DLP layer security.
        :type datalosspreventionstate: str
        :param filternoisydomains: Filter out domains that generate a lot of insignificant traffic (noise).
        :type filternoisydomains: bool
        :param timezone: Display the timestamp of the traffic events in the specified timezone. For the timezone, provide a continent and city separated by an url-encoded forward slash ('/'), for example: timezone='ASIA%2fCALCUTTA'.
        :type timezone: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._get_requests_by_hour_serialize(
            var_from=var_from,
            to=to,
            limit=limit,
            offset=offset,
            domains=domains,
            urls=urls,
            categories=categories,
            policycategories=policycategories,
            ip=ip,
            ports=ports,
            identityids=identityids,
            identitytypes=identitytypes,
            applicationid=applicationid,
            verdict=verdict,
            sha256=sha256,
            securityoverridden=securityoverridden,
            bundleid=bundleid,
            threats=threats,
            threattypes=threattypes,
            ampdisposition=ampdisposition,
            antivirusthreats=antivirusthreats,
            datalosspreventionstate=datalosspreventionstate,
            filternoisydomains=filternoisydomains,
            timezone=timezone,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "GetRequestsByHour200Response",
            '400': "Reporting400Error",
            '401': "Reporting401Error",
            '403': "Reporting403Error",
            '404': "Reporting404Error",
            '500': "Reporting500Error",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    def get_requests_by_hour_without_preload_content(
        self,
        var_from: Annotated[StrictStr, Field(description="A timestamp or relative time string (for example: '-1days'). Filter for data that appears after this time.")],
        to: Annotated[StrictStr, Field(description="A timestamp or relative time string (for example: 'now'). Filter for data that appears before this time.")],
        limit: Annotated[Union[StrictFloat, StrictInt], Field(description="The maximum number of records to return from the collection.")],
        offset: Annotated[Optional[Union[StrictFloat, StrictInt]], Field(description="A number that represents an index in the collection.")] = None,
        domains: Annotated[Optional[StrictStr], Field(description="A domain name or comma-delimited list of domain name.")] = None,
        urls: Annotated[Optional[StrictStr], Field(description="A URL or comma-delimited list of URL.")] = None,
        categories: Annotated[Optional[StrictStr], Field(description="A category ID or comma-delimited list of category ID.")] = None,
        policycategories: Annotated[Optional[StrictStr], Field(description="A category ID or comma-delimited list of category ID. Filter the request by the categories that trigger a policy.")] = None,
        ip: Annotated[Optional[StrictStr], Field(description="An IP address.")] = None,
        ports: Annotated[Optional[StrictStr], Field(description="A port number or comma-delimited list of port numbers.")] = None,
        identityids: Annotated[Optional[StrictStr], Field(description="An identity ID or comma-delimited list of identity IDs.")] = None,
        identitytypes: Annotated[Optional[StrictStr], Field(description="An identity type or comma-delimited list of identity types.")] = None,
        applicationid: Annotated[Optional[StrictStr], Field(description="The ID of the application.")] = None,
        verdict: Annotated[Optional[StrictStr], Field(description="A string or comma-delimited string that describes whether the traffic can reach the destination.")] = None,
        sha256: Annotated[Optional[StrictStr], Field(description="A SHA-256 hash.")] = None,
        securityoverridden: Annotated[Optional[StrictBool], Field(description="Specify whether to filter on requests that override security.")] = None,
        bundleid: Annotated[Optional[Union[StrictFloat, StrictInt]], Field(description="A proxy bundle ID.")] = None,
        threats: Annotated[Optional[StrictStr], Field(description="A threat name or comma-delimited list of threat names.")] = None,
        threattypes: Annotated[Optional[StrictStr], Field(description="A threat type or comma-delimited list of threat types.")] = None,
        ampdisposition: Annotated[Optional[StrictStr], Field(description="An AMP disposition string or a comma-delimited list of AMP disposition strings.")] = None,
        antivirusthreats: Annotated[Optional[StrictStr], Field(description="A threat name or comma-delimited list of threat names.")] = None,
        datalosspreventionstate: Annotated[Optional[StrictStr], Field(description="A string that describes the status of a destination. Filter for requests that are blocked by the DLP layer security.")] = None,
        filternoisydomains: Annotated[Optional[StrictBool], Field(description="Filter out domains that generate a lot of insignificant traffic (noise).")] = None,
        timezone: Annotated[Optional[StrictStr], Field(description="Display the timestamp of the traffic events in the specified timezone. For the timezone, provide a continent and city separated by an url-encoded forward slash ('/'), for example: timezone='ASIA%2fCALCUTTA'.")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """Get Requests by Hour (All)

        List the activity volume within the timeframe.  **Access Scope:** Reports > Granular Events > Read-Only

        :param var_from: A timestamp or relative time string (for example: '-1days'). Filter for data that appears after this time. (required)
        :type var_from: str
        :param to: A timestamp or relative time string (for example: 'now'). Filter for data that appears before this time. (required)
        :type to: str
        :param limit: The maximum number of records to return from the collection. (required)
        :type limit: float
        :param offset: A number that represents an index in the collection.
        :type offset: float
        :param domains: A domain name or comma-delimited list of domain name.
        :type domains: str
        :param urls: A URL or comma-delimited list of URL.
        :type urls: str
        :param categories: A category ID or comma-delimited list of category ID.
        :type categories: str
        :param policycategories: A category ID or comma-delimited list of category ID. Filter the request by the categories that trigger a policy.
        :type policycategories: str
        :param ip: An IP address.
        :type ip: str
        :param ports: A port number or comma-delimited list of port numbers.
        :type ports: str
        :param identityids: An identity ID or comma-delimited list of identity IDs.
        :type identityids: str
        :param identitytypes: An identity type or comma-delimited list of identity types.
        :type identitytypes: str
        :param applicationid: The ID of the application.
        :type applicationid: str
        :param verdict: A string or comma-delimited string that describes whether the traffic can reach the destination.
        :type verdict: str
        :param sha256: A SHA-256 hash.
        :type sha256: str
        :param securityoverridden: Specify whether to filter on requests that override security.
        :type securityoverridden: bool
        :param bundleid: A proxy bundle ID.
        :type bundleid: float
        :param threats: A threat name or comma-delimited list of threat names.
        :type threats: str
        :param threattypes: A threat type or comma-delimited list of threat types.
        :type threattypes: str
        :param ampdisposition: An AMP disposition string or a comma-delimited list of AMP disposition strings.
        :type ampdisposition: str
        :param antivirusthreats: A threat name or comma-delimited list of threat names.
        :type antivirusthreats: str
        :param datalosspreventionstate: A string that describes the status of a destination. Filter for requests that are blocked by the DLP layer security.
        :type datalosspreventionstate: str
        :param filternoisydomains: Filter out domains that generate a lot of insignificant traffic (noise).
        :type filternoisydomains: bool
        :param timezone: Display the timestamp of the traffic events in the specified timezone. For the timezone, provide a continent and city separated by an url-encoded forward slash ('/'), for example: timezone='ASIA%2fCALCUTTA'.
        :type timezone: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._get_requests_by_hour_serialize(
            var_from=var_from,
            to=to,
            limit=limit,
            offset=offset,
            domains=domains,
            urls=urls,
            categories=categories,
            policycategories=policycategories,
            ip=ip,
            ports=ports,
            identityids=identityids,
            identitytypes=identitytypes,
            applicationid=applicationid,
            verdict=verdict,
            sha256=sha256,
            securityoverridden=securityoverridden,
            bundleid=bundleid,
            threats=threats,
            threattypes=threattypes,
            ampdisposition=ampdisposition,
            antivirusthreats=antivirusthreats,
            datalosspreventionstate=datalosspreventionstate,
            filternoisydomains=filternoisydomains,
            timezone=timezone,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "GetRequestsByHour200Response",
            '400': "Reporting400Error",
            '401': "Reporting401Error",
            '403': "Reporting403Error",
            '404': "Reporting404Error",
            '500': "Reporting500Error",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _get_requests_by_hour_serialize(
        self,
        var_from,
        to,
        limit,
        offset,
        domains,
        urls,
        categories,
        policycategories,
        ip,
        ports,
        identityids,
        identitytypes,
        applicationid,
        verdict,
        sha256,
        securityoverridden,
        bundleid,
        threats,
        threattypes,
        ampdisposition,
        antivirusthreats,
        datalosspreventionstate,
        filternoisydomains,
        timezone,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[
            str, Union[str, bytes, List[str], List[bytes], List[Tuple[str, bytes]]]
        ] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        # process the query parameters
        if var_from is not None:
            
            _query_params.append(('from', var_from))
            
        if to is not None:
            
            _query_params.append(('to', to))
            
        if limit is not None:
            
            _query_params.append(('limit', limit))
            
        if offset is not None:
            
            _query_params.append(('offset', offset))
            
        if domains is not None:
            
            _query_params.append(('domains', domains))
            
        if urls is not None:
            
            _query_params.append(('urls', urls))
            
        if categories is not None:
            
            _query_params.append(('categories', categories))
            
        if policycategories is not None:
            
            _query_params.append(('policycategories', policycategories))
            
        if ip is not None:
            
            _query_params.append(('ip', ip))
            
        if ports is not None:
            
            _query_params.append(('ports', ports))
            
        if identityids is not None:
            
            _query_params.append(('identityids', identityids))
            
        if identitytypes is not None:
            
            _query_params.append(('identitytypes', identitytypes))
            
        if applicationid is not None:
            
            _query_params.append(('applicationid', applicationid))
            
        if verdict is not None:
            
            _query_params.append(('verdict', verdict))
            
        if sha256 is not None:
            
            _query_params.append(('sha256', sha256))
            
        if securityoverridden is not None:
            
            _query_params.append(('securityoverridden', securityoverridden))
            
        if bundleid is not None:
            
            _query_params.append(('bundleid', bundleid))
            
        if threats is not None:
            
            _query_params.append(('threats', threats))
            
        if threattypes is not None:
            
            _query_params.append(('threattypes', threattypes))
            
        if ampdisposition is not None:
            
            _query_params.append(('ampdisposition', ampdisposition))
            
        if antivirusthreats is not None:
            
            _query_params.append(('antivirusthreats', antivirusthreats))
            
        if datalosspreventionstate is not None:
            
            _query_params.append(('datalosspreventionstate', datalosspreventionstate))
            
        if filternoisydomains is not None:
            
            _query_params.append(('filternoisydomains', filternoisydomains))
            
        if timezone is not None:
            
            _query_params.append(('timezone', timezone))
            
        # process the header parameters
        # process the form parameters
        # process the body parameter


        # set the HTTP header `Accept`
        if 'Accept' not in _header_params:
            _header_params['Accept'] = self.api_client.select_header_accept(
                [
                    'application/json'
                ]
            )


        # authentication setting
        _auth_settings: List[str] = [
            'oauthFlow'
        ]

        return self.api_client.param_serialize(
            method='GET',
            resource_path='/reports/v2/requests-by-hour',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )


