# coding: utf-8

"""
    Cisco Secure Access API

    Unified OpenAPI spec for Cisco Secure Access APIs.

    The version of the OpenAPI document: 1.0.0
    Contact: devnet@cisco.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

import warnings
from pydantic import validate_call, Field, StrictFloat, StrictStr, StrictInt
from typing import Any, Dict, List, Optional, Tuple, Union
from typing_extensions import Annotated

from pydantic import Field, StrictInt, StrictStr
from typing import Optional
from typing_extensions import Annotated
from secure_access.models.list_unified_network_objects200_response import ListUnifiedNetworkObjects200Response
from secure_access.models.list_unified_service_objects200_response import ListUnifiedServiceObjects200Response

from secure_access.api_client import ApiClient, RequestSerialized
from secure_access.api_response import ApiResponse
from secure_access.rest import RESTResponseType


class UnifiedObjectsApi:
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    def __init__(self, api_client=None) -> None:
        if api_client is None:
            api_client = ApiClient.get_default()
        self.api_client = api_client


    @validate_call
    def list_unified_network_objects(
        self,
        offset: Annotated[Optional[StrictInt], Field(description="The place to start reading in the collection. The offset starts at 0. If the `limit` is 10, the offset for the next response is 10. The default value is 0.")] = None,
        limit: Annotated[Optional[StrictInt], Field(description="The maximum number of items from the collection to return in the response. The default value is 10.")] = None,
        name: Annotated[Optional[StrictStr], Field(description="The name of an object.")] = None,
        description: Annotated[Optional[StrictStr], Field(description="A meaningful description for an object.")] = None,
        value: Annotated[Optional[StrictStr], Field(description="The list of addresses to query the Network Object.")] = None,
        type: Annotated[Optional[StrictStr], Field(description="The types of the Network Objects and Network Object Groups. A string with a single value of the Network Object's type or `group`, or a comma-separated string that includes the values of the types for the Network Objects and the type of `group`. Valid values of the object types are: `host`, `network`, `range`, or `fqdn`.")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ListUnifiedNetworkObjects200Response:
        """List Network Objects and Network Groups

        Get the Network Objects and Network Object Groups in the organization.

        :param offset: The place to start reading in the collection. The offset starts at 0. If the `limit` is 10, the offset for the next response is 10. The default value is 0.
        :type offset: int
        :param limit: The maximum number of items from the collection to return in the response. The default value is 10.
        :type limit: int
        :param name: The name of an object.
        :type name: str
        :param description: A meaningful description for an object.
        :type description: str
        :param value: The list of addresses to query the Network Object.
        :type value: str
        :param type: The types of the Network Objects and Network Object Groups. A string with a single value of the Network Object's type or `group`, or a comma-separated string that includes the values of the types for the Network Objects and the type of `group`. Valid values of the object types are: `host`, `network`, `range`, or `fqdn`.
        :type type: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._list_unified_network_objects_serialize(
            offset=offset,
            limit=limit,
            name=name,
            description=description,
            value=value,
            type=type,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "ListUnifiedNetworkObjects200Response",
            '400': "Model400ErrorObject",
            '401': "Model401ErrorObject",
            '403': "Model403ErrorObject",
            '404': "Model404ErrorObject",
            '500': "Model500ErrorObject",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    def list_unified_network_objects_with_http_info(
        self,
        offset: Annotated[Optional[StrictInt], Field(description="The place to start reading in the collection. The offset starts at 0. If the `limit` is 10, the offset for the next response is 10. The default value is 0.")] = None,
        limit: Annotated[Optional[StrictInt], Field(description="The maximum number of items from the collection to return in the response. The default value is 10.")] = None,
        name: Annotated[Optional[StrictStr], Field(description="The name of an object.")] = None,
        description: Annotated[Optional[StrictStr], Field(description="A meaningful description for an object.")] = None,
        value: Annotated[Optional[StrictStr], Field(description="The list of addresses to query the Network Object.")] = None,
        type: Annotated[Optional[StrictStr], Field(description="The types of the Network Objects and Network Object Groups. A string with a single value of the Network Object's type or `group`, or a comma-separated string that includes the values of the types for the Network Objects and the type of `group`. Valid values of the object types are: `host`, `network`, `range`, or `fqdn`.")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[ListUnifiedNetworkObjects200Response]:
        """List Network Objects and Network Groups

        Get the Network Objects and Network Object Groups in the organization.

        :param offset: The place to start reading in the collection. The offset starts at 0. If the `limit` is 10, the offset for the next response is 10. The default value is 0.
        :type offset: int
        :param limit: The maximum number of items from the collection to return in the response. The default value is 10.
        :type limit: int
        :param name: The name of an object.
        :type name: str
        :param description: A meaningful description for an object.
        :type description: str
        :param value: The list of addresses to query the Network Object.
        :type value: str
        :param type: The types of the Network Objects and Network Object Groups. A string with a single value of the Network Object's type or `group`, or a comma-separated string that includes the values of the types for the Network Objects and the type of `group`. Valid values of the object types are: `host`, `network`, `range`, or `fqdn`.
        :type type: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._list_unified_network_objects_serialize(
            offset=offset,
            limit=limit,
            name=name,
            description=description,
            value=value,
            type=type,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "ListUnifiedNetworkObjects200Response",
            '400': "Model400ErrorObject",
            '401': "Model401ErrorObject",
            '403': "Model403ErrorObject",
            '404': "Model404ErrorObject",
            '500': "Model500ErrorObject",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    def list_unified_network_objects_without_preload_content(
        self,
        offset: Annotated[Optional[StrictInt], Field(description="The place to start reading in the collection. The offset starts at 0. If the `limit` is 10, the offset for the next response is 10. The default value is 0.")] = None,
        limit: Annotated[Optional[StrictInt], Field(description="The maximum number of items from the collection to return in the response. The default value is 10.")] = None,
        name: Annotated[Optional[StrictStr], Field(description="The name of an object.")] = None,
        description: Annotated[Optional[StrictStr], Field(description="A meaningful description for an object.")] = None,
        value: Annotated[Optional[StrictStr], Field(description="The list of addresses to query the Network Object.")] = None,
        type: Annotated[Optional[StrictStr], Field(description="The types of the Network Objects and Network Object Groups. A string with a single value of the Network Object's type or `group`, or a comma-separated string that includes the values of the types for the Network Objects and the type of `group`. Valid values of the object types are: `host`, `network`, `range`, or `fqdn`.")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """List Network Objects and Network Groups

        Get the Network Objects and Network Object Groups in the organization.

        :param offset: The place to start reading in the collection. The offset starts at 0. If the `limit` is 10, the offset for the next response is 10. The default value is 0.
        :type offset: int
        :param limit: The maximum number of items from the collection to return in the response. The default value is 10.
        :type limit: int
        :param name: The name of an object.
        :type name: str
        :param description: A meaningful description for an object.
        :type description: str
        :param value: The list of addresses to query the Network Object.
        :type value: str
        :param type: The types of the Network Objects and Network Object Groups. A string with a single value of the Network Object's type or `group`, or a comma-separated string that includes the values of the types for the Network Objects and the type of `group`. Valid values of the object types are: `host`, `network`, `range`, or `fqdn`.
        :type type: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._list_unified_network_objects_serialize(
            offset=offset,
            limit=limit,
            name=name,
            description=description,
            value=value,
            type=type,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "ListUnifiedNetworkObjects200Response",
            '400': "Model400ErrorObject",
            '401': "Model401ErrorObject",
            '403': "Model403ErrorObject",
            '404': "Model404ErrorObject",
            '500': "Model500ErrorObject",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _list_unified_network_objects_serialize(
        self,
        offset,
        limit,
        name,
        description,
        value,
        type,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[
            str, Union[str, bytes, List[str], List[bytes], List[Tuple[str, bytes]]]
        ] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        # process the query parameters
        if offset is not None:
            
            _query_params.append(('offset', offset))
            
        if limit is not None:
            
            _query_params.append(('limit', limit))
            
        if name is not None:
            
            _query_params.append(('name', name))
            
        if description is not None:
            
            _query_params.append(('description', description))
            
        if value is not None:
            
            _query_params.append(('value', value))
            
        if type is not None:
            
            _query_params.append(('type', type))
            
        # process the header parameters
        # process the form parameters
        # process the body parameter


        # set the HTTP header `Accept`
        if 'Accept' not in _header_params:
            _header_params['Accept'] = self.api_client.select_header_accept(
                [
                    'application/json'
                ]
            )


        # authentication setting
        _auth_settings: List[str] = [
            'oauthFlow'
        ]

        return self.api_client.param_serialize(
            method='GET',
            resource_path='/policies/v2/objects/unifiedNetworkObjects',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )




    @validate_call
    def list_unified_service_objects(
        self,
        offset: Annotated[Optional[StrictInt], Field(description="The place to start reading in the collection. The offset starts at 0. If the `limit` is 10, the offset for the next response is 10. The default value is 0.")] = None,
        limit: Annotated[Optional[StrictInt], Field(description="The maximum number of items from the collection to return in the response. The default value is 10.")] = None,
        name: Annotated[Optional[StrictStr], Field(description="The name of an object.")] = None,
        description: Annotated[Optional[StrictStr], Field(description="A meaningful description for an object.")] = None,
        value: Annotated[Optional[StrictStr], Field(description="The list of addresses to query the Network Object.")] = None,
        type: Annotated[Optional[StrictStr], Field(description="The types of the Service Objects and Service Object Groups. A string with a single value of the Service Object's protocol or `group`, or a comma-separated string that includes the values of the protocols for the Service Objects and the type of `group`. Valid values of the protocols are: `tcp`, `udp`, `icmp`, or `any`.")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ListUnifiedServiceObjects200Response:
        """List Service Objects and Service Groups

        Get the Service Objects and Service Object Groups in the organization.

        :param offset: The place to start reading in the collection. The offset starts at 0. If the `limit` is 10, the offset for the next response is 10. The default value is 0.
        :type offset: int
        :param limit: The maximum number of items from the collection to return in the response. The default value is 10.
        :type limit: int
        :param name: The name of an object.
        :type name: str
        :param description: A meaningful description for an object.
        :type description: str
        :param value: The list of addresses to query the Network Object.
        :type value: str
        :param type: The types of the Service Objects and Service Object Groups. A string with a single value of the Service Object's protocol or `group`, or a comma-separated string that includes the values of the protocols for the Service Objects and the type of `group`. Valid values of the protocols are: `tcp`, `udp`, `icmp`, or `any`.
        :type type: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._list_unified_service_objects_serialize(
            offset=offset,
            limit=limit,
            name=name,
            description=description,
            value=value,
            type=type,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "ListUnifiedServiceObjects200Response",
            '400': "Model400ErrorObject",
            '401': "Model401ErrorObject",
            '403': "Model403ErrorObject",
            '404': "Model404ErrorObject",
            '500': "Model500ErrorObject",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    def list_unified_service_objects_with_http_info(
        self,
        offset: Annotated[Optional[StrictInt], Field(description="The place to start reading in the collection. The offset starts at 0. If the `limit` is 10, the offset for the next response is 10. The default value is 0.")] = None,
        limit: Annotated[Optional[StrictInt], Field(description="The maximum number of items from the collection to return in the response. The default value is 10.")] = None,
        name: Annotated[Optional[StrictStr], Field(description="The name of an object.")] = None,
        description: Annotated[Optional[StrictStr], Field(description="A meaningful description for an object.")] = None,
        value: Annotated[Optional[StrictStr], Field(description="The list of addresses to query the Network Object.")] = None,
        type: Annotated[Optional[StrictStr], Field(description="The types of the Service Objects and Service Object Groups. A string with a single value of the Service Object's protocol or `group`, or a comma-separated string that includes the values of the protocols for the Service Objects and the type of `group`. Valid values of the protocols are: `tcp`, `udp`, `icmp`, or `any`.")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[ListUnifiedServiceObjects200Response]:
        """List Service Objects and Service Groups

        Get the Service Objects and Service Object Groups in the organization.

        :param offset: The place to start reading in the collection. The offset starts at 0. If the `limit` is 10, the offset for the next response is 10. The default value is 0.
        :type offset: int
        :param limit: The maximum number of items from the collection to return in the response. The default value is 10.
        :type limit: int
        :param name: The name of an object.
        :type name: str
        :param description: A meaningful description for an object.
        :type description: str
        :param value: The list of addresses to query the Network Object.
        :type value: str
        :param type: The types of the Service Objects and Service Object Groups. A string with a single value of the Service Object's protocol or `group`, or a comma-separated string that includes the values of the protocols for the Service Objects and the type of `group`. Valid values of the protocols are: `tcp`, `udp`, `icmp`, or `any`.
        :type type: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._list_unified_service_objects_serialize(
            offset=offset,
            limit=limit,
            name=name,
            description=description,
            value=value,
            type=type,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "ListUnifiedServiceObjects200Response",
            '400': "Model400ErrorObject",
            '401': "Model401ErrorObject",
            '403': "Model403ErrorObject",
            '404': "Model404ErrorObject",
            '500': "Model500ErrorObject",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    def list_unified_service_objects_without_preload_content(
        self,
        offset: Annotated[Optional[StrictInt], Field(description="The place to start reading in the collection. The offset starts at 0. If the `limit` is 10, the offset for the next response is 10. The default value is 0.")] = None,
        limit: Annotated[Optional[StrictInt], Field(description="The maximum number of items from the collection to return in the response. The default value is 10.")] = None,
        name: Annotated[Optional[StrictStr], Field(description="The name of an object.")] = None,
        description: Annotated[Optional[StrictStr], Field(description="A meaningful description for an object.")] = None,
        value: Annotated[Optional[StrictStr], Field(description="The list of addresses to query the Network Object.")] = None,
        type: Annotated[Optional[StrictStr], Field(description="The types of the Service Objects and Service Object Groups. A string with a single value of the Service Object's protocol or `group`, or a comma-separated string that includes the values of the protocols for the Service Objects and the type of `group`. Valid values of the protocols are: `tcp`, `udp`, `icmp`, or `any`.")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """List Service Objects and Service Groups

        Get the Service Objects and Service Object Groups in the organization.

        :param offset: The place to start reading in the collection. The offset starts at 0. If the `limit` is 10, the offset for the next response is 10. The default value is 0.
        :type offset: int
        :param limit: The maximum number of items from the collection to return in the response. The default value is 10.
        :type limit: int
        :param name: The name of an object.
        :type name: str
        :param description: A meaningful description for an object.
        :type description: str
        :param value: The list of addresses to query the Network Object.
        :type value: str
        :param type: The types of the Service Objects and Service Object Groups. A string with a single value of the Service Object's protocol or `group`, or a comma-separated string that includes the values of the protocols for the Service Objects and the type of `group`. Valid values of the protocols are: `tcp`, `udp`, `icmp`, or `any`.
        :type type: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._list_unified_service_objects_serialize(
            offset=offset,
            limit=limit,
            name=name,
            description=description,
            value=value,
            type=type,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "ListUnifiedServiceObjects200Response",
            '400': "Model400ErrorObject",
            '401': "Model401ErrorObject",
            '403': "Model403ErrorObject",
            '404': "Model404ErrorObject",
            '500': "Model500ErrorObject",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _list_unified_service_objects_serialize(
        self,
        offset,
        limit,
        name,
        description,
        value,
        type,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[
            str, Union[str, bytes, List[str], List[bytes], List[Tuple[str, bytes]]]
        ] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        # process the query parameters
        if offset is not None:
            
            _query_params.append(('offset', offset))
            
        if limit is not None:
            
            _query_params.append(('limit', limit))
            
        if name is not None:
            
            _query_params.append(('name', name))
            
        if description is not None:
            
            _query_params.append(('description', description))
            
        if value is not None:
            
            _query_params.append(('value', value))
            
        if type is not None:
            
            _query_params.append(('type', type))
            
        # process the header parameters
        # process the form parameters
        # process the body parameter


        # set the HTTP header `Accept`
        if 'Accept' not in _header_params:
            _header_params['Accept'] = self.api_client.select_header_accept(
                [
                    'application/json'
                ]
            )


        # authentication setting
        _auth_settings: List[str] = [
            'oauthFlow'
        ]

        return self.api_client.param_serialize(
            method='GET',
            resource_path='/policies/v2/objects/unifiedServiceObjects',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )


